manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nektariostsiounis
      url-base: https://github.com/nektariostsiounis
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-macropad-3x3-module
      remote: nektariostsiounis
      revision: main
  self:
    path: config